default:
  image: nixos/nix:latest
  before_script:
    - test ! -d .nix/cache && mkdir -p .nix/cache && cp -r /nix/store .nix/store
    - mount --bind .nix/cache /nix/store
  timeout: 2 hours
  cache:
    paths:
      - .nix

variables:
  GIT_SUBMODULE_STRATEGY: recursive

nix:
  script:
    - nix-build
  stage: build
