stages:
  - build
  - build-libs

default:
  image: nixos/nix:latest
  before_script:
    - mkdir .nix
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
    - if [ -f $LOCAL_NIX_STORE ]; then tar -xkzf $LOCAL_NIX_STORE -C /; fi
  after_script:
    - tar -czf $LOCAL_NIX_STORE /nix/store
  cache:
    paths:
      - .nix/

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LOCAL_NIX_STORE: $CI_PROJECT_DIR/.nix/store

omnetpp:
  script:
    - nix-build pkgs.nix -A omnetpp
  stage: build
  only:
    - tags

# inet:
#   script:
#     - nix-build pkgs.nix -A inet
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
#
# ops:
#   script:
#     - nix-build pkgs.nix -A ops
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
