stages:
  - build
  - build-libs

default:
  image: nixos/nix:latest
  before_script:
    - if [ -e .gitlab-cache.tar.gz ]; then rm -rf /nix || true; fi
    - if [ -e .gitlab-cache.tar.gz ]; then tar -xzf .gitlab-cache.tar.gz -C / || true; fi
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
  after_script:
    - tar -czf .gitlab-cache.tar.gz /nix || true
  cache:
    paths:
      - .gitlab-cache.tar.gz

variables:
  GIT_SUBMODULE_STRATEGY: recursive

omnetpp:
  script:
    - nix-build pkgs.nix -A omnetpp
  stage: build
  only:
    - tags

inet:
  script:
    - nix-build pkgs.nix -A inet
  dependencies:
    - omnetpp
  stage: build-libs
  only:
    - tags

ops:
  script:
    - nix-build pkgs.nix -A ops
  dependencies:
    - omnetpp
  stage: build-libs
  only:
    - tags
