stages:
  - build
  - build-libs

default:
  image: nixos/nix:latest
  before_script:
    - nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
    - nix-channel --update
  cache:
    paths:
      - .nix/

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  NIX_STORE_DIR: $CI_PROJECT_DIR/.nix

omnetpp:
  script:
    - nix-build pkgs.nix -A omnetpp
  stage: build
  only:
    - tags

inet:
  script:
    - nix-build pkgs.nix -A inet
  dependencies:
    - omnetpp
  stage: build-libs
  only:
    - tags

ops:
  script:
    - nix-build pkgs.nix -A ops
  dependencies:
    - omnetpp
  stage: build-libs
  only:
    - tags
