stages:
  - build
  - build-libs

default:
  image: nixos/nix:latest
  before_script:
    - nix-env -iA nixpkgs.cachix nixpkgs.bash
    - cachix use omnetpp-nix
    - nix path-info --all > /tmp/store-path-pre-build
  after_script:
    - bash -c "comm -13 <(sort /tmp/store-path-pre-build | grep -v '\.drv$') <(nix path-info --all | grep -v '\.drv$' | sort) | cachix push omnetpp-nix"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

omnetpp:
  script:
    - nix-build pkgs.nix -A omnetpp
  stage: build
  only:
    - tags

# inet:
#   script:
#     - nix-build pkgs.nix -A inet
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
#
# ops:
#   script:
#     - nix-build pkgs.nix -A ops
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
