stages:
  - build
  - build-libs

default:
  image: nixos/nix:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

omnetpp:
  script:
    - nix-build pkgs.nix -A omnetpp
  stage: build
  only:
    - tags

# inet:
#   script:
#     - nix-build pkgs.nix -A inet
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
#
# ops:
#   script:
#     - nix-build pkgs.nix -A ops
#   dependencies:
#     - omnetpp
#   stage: build-libs
#   only:
#     - tags
