default:
  image: nixos/nix:latest
  before_script:
    - test ! -d .nix/store && mkdir -p .nix/store
    - ln -sf /nix/store/* .nix/store
    - mount --bind .nix/store /nix/store
  after_script:
    - find .nix/store -type l | xargs rm
  cache:
    paths:
      - .nix

variables:
  GIT_SUBMODULE_STRATEGY: recursive

nix:
  script:
    - nix-build
  stage: build
