default:
  image: nixos/nix:latest
  cache:
    paths:
      - .nix

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  LOCAL_NIX_STORE: $CI_PROJECT_DIR/.nix/store

nix:
  before_script:
    - nix-channel --add https://nixos.org/channels/nixpkgs nixpkgs
    - nix-channel --update
    - mkdir -p $LOCAL_NIX_STORE
    - mkdir -p /etc/nix
    - echo "substituters = https://cache.nixos.org/ file://$LOCAL_NIX_STORE" | tee -a /etc/nix/nix.conf > /dev/null
    - echo 'require-sigs = false' | tee -a /etc/nix/nix.conf > /dev/null
  script:
    - nix-build
    # or use  `nix-build -E "(import <nixpkgs> {}).somePackages.callPackage ./. {}"`
  after_script:
    - nix copy --to file://$LOCAL_NIX_STORE --all
  stage: build
  only:
    - master
