default:
  image: nixos/nix:latest
  before_script:
    - test ! -d .nix/cache && mkdir -p .nix/cache
    - test ! -d /nix/store && mkdir /nix/store
    - echo origin nix store && ls /nix/store
    - mount --bind .nix/cache /nix/store
  timeout: 2 hours
  cache:
    paths:
      - .nix

variables:
  GIT_SUBMODULE_STRATEGY: recursive

nix:
  script:
    - nix-build
  stage: build
